### ISSUE TITLE
How to use models.FileField()?

### ISSUE THREAD

**Issue by jwl317** [skkuse/2020spring_41class_team9#10]
When I worked on model.py, I used this [link](https://wayhome25.github.io/django/2017/03/20/django-ep5-model/
) as a reference to define the fields.

In case of Developer, we decided to have two entities - profile image and portfolio - from the Design Specification.

`
profile_image = models.FileField(
        verbose_name='profile image',
        upload_to="developer/profile_pic", #not sure
    )
`

When the user uploads his profile image, I remember it will be stored in our modu database.
I'm a little lost here... where will profile image be uploaded to?
I'm not so sure about models.FileField() either.
Any ideas?

**Comment by ReverseIdeology** [comment]
**Use [`django.db.models.ImageField`](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ImageField).**
Also, uploaded images will be stored in volume (HDD, SDD or something else) directly, not database. Check [Reference](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.FileField.storage) and read [how to manage files for `FileField`/`ImageField`](https://docs.djangoproject.com/en/3.0/topics/files/).

**Comment by jwl317** [comment]
> **Use [`django.db.models.ImageField`](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ImageField).**
> Also, uploaded images will be stored in volume (HDD, SDD or something else) directly, not database. Check [Reference](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.FileField.storage) and read [how to manage files for `FileField`/`ImageField`](https://docs.djangoproject.com/en/3.0/topics/files/).

Thank you for sharing the reference!
Let me try it first.

**Comment by jwl317** [comment]
> **Use [`django.db.models.ImageField`](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ImageField).**
> Also, uploaded images will be stored in volume (HDD, SDD or something else) directly, not database. Check [Reference](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.FileField.storage) and read [how to manage files for `FileField`/`ImageField`](https://docs.djangoproject.com/en/3.0/topics/files/).

When using ImageField, Pillow must be installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
