### ISSUE TITLE
No uniqueness validation and self referencing prevention with django ManyToManyField model.

### ISSUE THREAD

**Issue by ReverseIdeology** [skkuse/2020spring_41class_team9#18]
**To ensure uniqueness,** we should use `unique_together` with 'through model' like:
``` python
class M2MModel(models.Model):
    field1 = models.ForeignKey(Model1)
    field2 = models.ForeignKey(Model2)
    class Meta:
        unique_together = ('field1', 'field2')
```
and
``` python
others = models.ManyToManyField('some classes', through = 'M2MModel')
```

**To prohibit self referencing** (in object view), [we can redefine save function to raise validation error if validation fails.](https://stackoverflow.com/questions/43308976/django-model-self-reference-prevent-referencing-to-itself)

**Comment by jwl317** [comment]
I think this is quite important for all of us to know when dealing with many to many relationships.

It is interesting how save function is delt with. So we either

1) define the save function to show an error when returning its own object

or

2) write it in the meta data section using `unique_together`

Is that right?

**Comment by ReverseIdeology** [comment]
**NO.** We should use both.
1. To ensure uniqueness of ManyToManyField, the example class `M2MModel` **MUST** be applied as a through model of target `ManyToManyField`.

2. In addition, we should consider self-referencing.
If the `ManyToManyField` of an object should not reference the object itself, we should implement that class to raise error when objects are trying to add themselves as a referencing target, by redefining save function, or using other features of django model class.

\+
Reading the official guidelines, I found the [suitable functionality to apply constraints](https://docs.djangoproject.com/en/3.0/ref/models/options/#constraints). Rather than redefining `save` function, adding meta constraints is much shorter & easier, and looks very nice.

**Comment by jwl317** [comment]
> **NO.** We should use both.
> 
> 1. To ensure uniqueness of ManyToManyField, the example class `M2MModel` **MUST** be applied as a through model of target `ManyToManyField`.
> 2. In addition, we should consider self-referencing.
>    If the `ManyToManyField` of an object should not reference the object itself, we should implement that class to raise error when objects are trying to add themselves as a referencing target, by redefining save function, or using other features of django model class.
> 
> +
> Reading the official guidelines, I found the [suitable functionality to apply constraints](https://docs.djangoproject.com/en/3.0/ref/models/options/#constraints). Rather than redefining `save` function, adding meta constraints is much shorter & easier, and looks very nice.

Thank you for your clarification!
I worked on the `M2MModels` and updated in `models.py` under the branch `feature/invitation_management`.
Please check it out when you are available.
