### ISSUE TITLE
Are there three cases upon accepting invitations?

### ISSUE THREAD

**Issue by jwl317** [skkuse/2020spring_41class_team9#22]
There are two functions in `views.py`.

> 1. `invite(request, userID)` : this function is needed when a developer invites another developer to join a project
> 2. `invitationAccept(request, userID)` : this function is needed when a developer receives invitations and need to decide whether to accept or reject them

In `invitationAccept(request, userID)` , I thought of three cases. They are not stated in the Design Specification. So I need your opinions on the cases below.

> 1. If the developer has already accepted the invitation, then the invitation is removed from the list of invitations.
> 2. If the developer rejects the invitation, then the invitation is removed from the list of invitations.
> 3. If the developer does not decide, then the invitation stays.

**Comment by ReverseIdeology** [comment]
In terms of input parameters, yes.
Successful `invitationAccept(request, userID)` should be called with only two cases (**Accept** or **Reject**). If the function was called without the type of the action, the function should return error code 40x (such as 403 or 404 etc.).

However, in terms of the invitation status, result of accept and reject vary in two cases.
If the invitation exists in the list, the action would success. And if not, the action would fail.
If the developer has already accepted or rejected the invitation, there should be no targeting invitation in the list as the first request removes the invitation from the list, and subsequent request should return fail.
