### ISSUE TITLE
How about dividing the message model into user message and system notification models?

### ISSUE THREAD

**Issue by ReverseIdeology** [skkuse/2020spring_41class_team9#7]
Initially, we decided to use message object to represent both user messages and system notifications. However, as we use django model instead of database table directly, I think that dividing one unified message object into two concrete models is better than using one unified model.
Because we don't have user or superuser model as we use firebase REST API for the authentication, the sender field should be nullable, and this may result database in be invalid if we use one unified message model. . To avoid nullable sender field, we must divide role into two models; UserMessage and SystemNotification.

**Comment by jwl317** [comment]
I agree with dividing into two separate models.
If others agree, we can start making the additional models ASAP.

**Comment by JTzzang** [comment]
I agree too! It seems ok to me.

**Comment by ReverseIdeology** [comment]
Message separated in 848642b1731b97b5bd54803efdf701f392cf9030 and finally merged into [master](https://github.com/skkuse/2020spring_41class_team9/tree/master) branch.
